version: '3.7'
services:
  test-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 2
  test-redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 2
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      test-db:
        condition: service_healthy
      test-redis:
        condition: service_started
    command: >
      bash -c "
        cd src && alembic upgrade head && cd .. &&
        pytest tests/integration
      "
    environment:
      - DB_HOST=test-db
      - REDIS_HOST=test-redis
    volumes:
      - .:/app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 2

networks:
  app-network: